ifndef SIM_DIR
    $(error SIM_DIR is undefined)
endif

SIM_TOP		?= top
TARGET_SIM	?= $(SIM_DIR)/obj_dir/V$(SIM_TOP)
TARGET_FLAGS	?=
ifeq ($(shell command -v $(TARGET_SIM) 2> /dev/null),)
    $(error Target simulator executable '$(TARGET_SIM)' not found)
endif

RISCV_PREFIX	?= riscv64-unknown-elf-
RISCV_GCC	?= $(RISCV_PREFIX)gcc
RISCV_OBJCOPY	?= $(RISCV_PREFIX)objcopy
RISCV_GCC_OPTS	?= -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles

COMPILE_TARGET = \
	$$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) \
	-I$(ROOTDIR)/riscv-test-suite/env/ \
	-I$(TARGETDIR)/$(RISCV_TARGET)/ \
	-T$(TARGETDIR)/$(RISCV_TARGET)/link.ld $$< \
	-o $$@; \
	$$(RISCV_OBJCOPY) -O binary $$@ $(work_dir_isa)/$$*.bin; \
	hexdump -v -e '/4 "%08x\n"' $(work_dir_isa)/$$*.bin > $(work_dir_isa)/$$*.txt

RUN_TARGET = \
	$(TARGET_SIM) $(TARGET_FLAGS) \
	+data_file=$*.txt +dump_file=$*.dump > $@

