RISCV_PREFIX	?= riscv64-unknown-elf-
RISCV_GCC	?= $(RISCV_PREFIX)gcc
RISCV_OBJCOPY	?= $(RISCV_PREFIX)objcopy
RISCV_GCC_OPTS	?= -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles

COMPILE_TARGET = \
	$$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) \
	-I$(ROOTDIR)/riscv-test-suite/env/ \
	-I$(TARGETDIR)/$(RISCV_TARGET)/ \
	-T$(TARGETDIR)/$(RISCV_TARGET)/link.ld $$< \
	-o $$@; \
	$$(RISCV_OBJCOPY) -O binary $$@ $$@.bin

RUN_TARGET =

